[2021-05-23 02:02:25,089] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: marketvol.move_tsla_data_to_diff_location 2021-05-21T18:00:00+00:00 [queued]>
[2021-05-23 02:02:25,149] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: marketvol.move_tsla_data_to_diff_location 2021-05-21T18:00:00+00:00 [queued]>
[2021-05-23 02:02:25,150] {taskinstance.py:866} INFO - 
--------------------------------------------------------------------------------
[2021-05-23 02:02:25,152] {taskinstance.py:867} INFO - Starting attempt 1 of 3
[2021-05-23 02:02:25,153] {taskinstance.py:868} INFO - 
--------------------------------------------------------------------------------
[2021-05-23 02:02:25,172] {taskinstance.py:887} INFO - Executing <Task(BashOperator): move_tsla_data_to_diff_location> on 2021-05-21T18:00:00+00:00
[2021-05-23 02:02:25,183] {standard_task_runner.py:53} INFO - Started process 550 to run task
[2021-05-23 02:02:25,301] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: marketvol.move_tsla_data_to_diff_location 2021-05-21T18:00:00+00:00 [running]> c240d08e6ad5
[2021-05-23 02:02:25,341] {bash_operator.py:82} INFO - Tmp dir root location: 
 /tmp
[2021-05-23 02:02:25,344] {bash_operator.py:105} INFO - Temporary script location: /tmp/airflowtmp2ck0vfox/move_tsla_data_to_diff_locationl_ofrox2
[2021-05-23 02:02:25,346] {bash_operator.py:115} INFO - Running command: 
    mv $DATAPATH/2021-05-21/data_tsla.csv  /usr/local/finance_data/2021-05-21
[2021-05-23 02:02:25,359] {bash_operator.py:122} INFO - Output:
[2021-05-23 02:02:25,422] {bash_operator.py:130} INFO - Command exited with return code 0
[2021-05-23 02:02:25,444] {taskinstance.py:1048} INFO - Marking task as SUCCESS.dag_id=marketvol, task_id=move_tsla_data_to_diff_location, execution_date=20210521T180000, start_date=20210523T020225, end_date=20210523T020225
[2021-05-23 02:02:35,003] {logging_mixin.py:112} INFO - [2021-05-23 02:02:35,003] {local_task_job.py:103} INFO - Task exited with return code 0
[2021-05-23 04:51:32,718] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: marketvol.move_tsla_data_to_diff_location 2021-05-21T18:00:00+00:00 [queued]>
[2021-05-23 04:51:32,754] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: marketvol.move_tsla_data_to_diff_location 2021-05-21T18:00:00+00:00 [queued]>
[2021-05-23 04:51:32,755] {taskinstance.py:866} INFO - 
--------------------------------------------------------------------------------
[2021-05-23 04:51:32,756] {taskinstance.py:867} INFO - Starting attempt 1 of 3
[2021-05-23 04:51:32,757] {taskinstance.py:868} INFO - 
--------------------------------------------------------------------------------
[2021-05-23 04:51:32,772] {taskinstance.py:887} INFO - Executing <Task(BashOperator): move_tsla_data_to_diff_location> on 2021-05-21T18:00:00+00:00
[2021-05-23 04:51:32,776] {standard_task_runner.py:53} INFO - Started process 414 to run task
[2021-05-23 04:51:32,878] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: marketvol.move_tsla_data_to_diff_location 2021-05-21T18:00:00+00:00 [running]> 67459f5d81d7
[2021-05-23 04:51:32,911] {bash_operator.py:82} INFO - Tmp dir root location: 
 /tmp
[2021-05-23 04:51:32,914] {bash_operator.py:105} INFO - Temporary script location: /tmp/airflowtmpp4axkrbh/move_tsla_data_to_diff_locationj1eyzta0
[2021-05-23 04:51:32,915] {bash_operator.py:115} INFO - Running command: 
    mv $DATAPATH/2021-05-21/data_tsla.csv  /usr/local/finance_data/2021-05-21
[2021-05-23 04:51:32,925] {bash_operator.py:122} INFO - Output:
[2021-05-23 04:51:32,933] {bash_operator.py:126} INFO - mv: cannot create regular file '/usr/local/finance_data/2021-05-21': Permission denied
[2021-05-23 04:51:32,934] {bash_operator.py:130} INFO - Command exited with return code 1
[2021-05-23 04:51:32,947] {taskinstance.py:1128} ERROR - Bash command failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 966, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/bash_operator.py", line 134, in execute
    raise AirflowException("Bash command failed")
airflow.exceptions.AirflowException: Bash command failed
[2021-05-23 04:51:32,950] {taskinstance.py:1151} INFO - Marking task as UP_FOR_RETRY
[2021-05-23 04:51:42,682] {logging_mixin.py:112} INFO - [2021-05-23 04:51:42,681] {local_task_job.py:103} INFO - Task exited with return code 1
